### ISSUE TITLE
windows 10 list error

### ISSUE THREAD

**Issue by sheldon** [Theo47/depressurizer#16]
I got the following exception since upgrading to windows 10:

```
KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Depressurizer.FormMain.<InitializeLstGames>b__a(Object g)
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at BrightIdeasSoftware.ObjectListView.MakeSubItem(Object rowObject, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.FillInValues(OLVListItem lvi, Object rowObject)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Theo47** [comment]
I also have windows 10 and it works fine so that shouldn't be the real cause.
Can you delete the GameDB.xml.gz file as well the C:\Users\<username>\AppData\Roaming\Depressurizer folder and check if the problem persists?
Perhaps something got corrupted while you were upgrading to windows 10.
