### ISSUE TITLE
Fatal error: Culture is not supported.

### ISSUE THREAD

**Issue by lpchaim** [Theo47/depressurizer#169]
It'd seem the brazilian variant of Portuguese isn't handled correctly. Tried both with my existing install and a fresh one, the following error is reported. 
```
System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
pt_BR is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Depressurizer.Utility.GetCultureInfoFromStoreLanguage(StoreLanguage dbLanguage) in D:\Theo\Desktop\depressurizer\src\Depressurizer\Utility.cs:line 382
   at Depressurizer.FormMain.<>c.<InitializeLstGames>b__45_13(Object g) in D:\Theo\Desktop\depressurizer\src\Depressurizer\MainForm.cs:line 291
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at BrightIdeasSoftware.ObjectListView.MakeSubItem(Object rowObject, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.FillInValues(OLVListItem lvi, Object rowObject)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
[dError_20180814042409.log](https://github.com/Depressurizer/Depressurizer/files/2288218/dError_20180814042409.log)

**Comment by mvegter** [comment]
@lpchaim This is an inactive repo, you can check my fork of Depressurizer.
- [Source code](https://github.com/mvegter/Depressurizer)
- [Latest release](https://github.com/mvegter/Depressurizer/releases/latest)

**Comment by lpchaim** [comment]
I will, thanks @mvegter.
