### ISSUE TITLE
0.7.0. NullReferenceException on startup.

### ISSUE THREAD

**Issue by BuBByAU** [Theo47/depressurizer#27]
NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.SelectAutoCats(Settings settings)
   at Depressurizer.FormMain.FormMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at MaterialSkin.Controls.MaterialForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by BuBByAU** [comment]
Occurred only on initial launch - subsequent launch was ok.

**Comment by Theo47** [comment]
Fixed. https://github.com/Theo47/depressurizer/commit/24b315e9f890b21ecba237388210a3c7011d894b
