### ISSUE TITLE
Error Loading Profile during startup 0.7.1.1

### ISSUE THREAD

**Issue by BuBByAU** [Theo47/depressurizer#51]
Error loading profile.

Error loading profile.Data at the root level is invalid. Line 1, position 1.

NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.LoadProfile()
   at Depressurizer.FormMain.menu_File_LoadProfile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Theo47** [comment]
Can you upload your profile file? It should help on reproducing the error.
By default it is located at %USERPROFILE%\AppData\Roaming\Depressurizer and is named Default.profile.

**Comment by Theo47** [comment]
Feel free to reopen this if you come back and still have this problem.
