### ISSUE TITLE
Applying a category to every game gave me this crash

### ISSUE THREAD

**Issue by Zhuinden** [Theo47/depressurizer#65]
at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at Depressurizer.FormMain.lstGames_FormatCell(Object sender, FormatCellEventArgs e)
   at BrightIdeasSoftware.ObjectListView.OnFormatCell(FormatCellEventArgs args)
   at BrightIdeasSoftware.ObjectListView.TriggerFormatCellEvents(Int32 rowIndex, Int32 displayIndex, OLVListItem olvi)
   at BrightIdeasSoftware.ObjectListView.PostProcessOneRow(Int32 rowIndex, Int32 displayIndex, OLVListItem olvi)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at BrightIdeasSoftware.ObjectListView.GetItem(Int32 index)
   at BrightIdeasSoftware.ObjectListView.HandleReflectNotify(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Zhuinden** [comment]
at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at Depressurizer.FormMain.lstGames_FormatCell(Object sender, FormatCellEventArgs e)
   at BrightIdeasSoftware.ObjectListView.OnFormatCell(FormatCellEventArgs args)
   at BrightIdeasSoftware.ObjectListView.TriggerFormatCellEvents(Int32 rowIndex, Int32 displayIndex, OLVListItem olvi)
   at BrightIdeasSoftware.ObjectListView.PostProcessOneRow(Int32 rowIndex, Int32 displayIndex, OLVListItem olvi)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at BrightIdeasSoftware.ObjectListView.GetItem(Int32 index)
   at BrightIdeasSoftware.ObjectListView.HandleReflectNotify(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

yep same one

**Comment by Theo47** [comment]
I think hymerman's update should fix this. (https://github.com/Theo47/depressurizer/pull/93)
