### ISSUE TITLE
NullReferenceException when loading profile

### ISSUE THREAD

**Issue by scowalt** [Theo47/depressurizer#78]
### Repro steps (100% repro)

1. On program first run (after locating the steam installation folder), hit cancel on the "Create a Profile" dialog.
2. On the main menu, click File > Load Profile
3. The program crashes with the following error:

```
NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.LoadProfile()
   at Depressurizer.FormMain.menu_File_LoadProfile_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Work-around
Instead of hitting cancel at the "Create a Profile" dialog, create a profile. This created profile doesn't need to be saved or modified to load a different profile.

**Comment by Theo47** [comment]
Fixed (06c45d41b08b70ccb1f64ef2db91b830240005b2).
